from tkinter import *
window = Tk()
window.title("Tkinter Sample Window")
window.geometry("300x300")
greeting=Label(text="Hello User",fg="cyan",bg="black")
button=Button(text="Click me",bg="black",fg="cyan")
entry=Entry(fg="cyan",bg="black",width=600000000)
greeting.pack()
button.pack()
button.pack()
frame=Frame(master=window,relief=RAISED,borderwidth=6)
frame.pack()
label=Label(master=frame,text="Sample Frame")
textbox=Text(fg="cyan",bg="black")
textbox.pack()
window.mainloop()