from tkinter import *
window = Tk()
window.title("Tkinter Sample Window")
window.geometry("300x300")
greeting=Label(text="Welcome to my application",fg="cyan",bg="black")
button=Button(text="Submit",bg="black",fg="cyan")
entry=Entry(text="Enter your name",fg="cyan",bg="black",width=600000000)
greeting.pack()
entry.pack()
button.pack()
frame=Frame(master=window,relief=RAISED,borderwidth=6)
frame.pack()
label=Label(master=frame,text="Thank you for registration")
label.pack()
window.mainloop()